export const ADD_CLIENT = 'ADD_CLIENT';
export const REMOVE_CLIENT = 'REMOVE_CLIENT';
export const SET_CLIENTS = 'SET_CLIENTS';
export const FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED';
export const SUCCESSFUL_SEARCH = 'SUCCESSFUL_SEARCH';
export const END_OF_SEARCH = 'END_OF_SEARCH';